### ISSUE TITLE
Problems with publishing branch

### ISSUE THREAD

**Issue by CharlieShing** [deltagruppen/circles#7]
I've created a branch in my git gui on the computer which contains all changes I've made so far. However when I try to publish it I get an error saying it isn't possible. Nothing else.
Tried writing "git push --set-upstream .\circles christoffer_first_layout" in the shell and got the error fatal: Not a git repository (or any of the parent directories). I tried deleting folder and cloning it again but got the same error.

**Comment by macaullyjames** [comment]
It looks like you haven't forked the deltagruppen/circles repo. Go to the [main page](https://github.com/deltagruppen/circles) and click "fork". Then, clone the repo and set up your remotes (see the comments in #4). You can't push to the upstream repo; push to your repo and send a PR.

Thanks for opening an issue, by the way :)

**Comment by CharlieShing** [comment]
Well, no problem except.
I don't get it. I've forked it. Then I cloned it. Then I copied all changed files into the cloned file. Then I tried adding upstream with "git remote add upstream https://github.com/ChristofferAB/circles.git" but it told me that was fatal and it already existed. So I pressed publish instead which worked this time. And the fork is displayed on github but when I try to make a PR it tells me that there is nothing that's changed. Does that mean that the files are already up?

**Comment by CharlieShing** [comment]
No it doesn't because the updated files are not there. What's up?

**Comment by CharlieShing** [comment]
I think I managed to get it working now. Used the gui and commited the files that I had pasted into the git repo folder. But I believe I commited to the develop branch instead of my own. Sorz.

**Comment by CharlieShing** [comment]
Sent an updated version in the right branch. Hope it works.
